# Generated by Django 4.2.5 on 2023-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrubs',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='scrubs',
            name='price',
            field=models.BigIntegerField(default=False),
        ),
    ]
